site_name: Progenetix Documentation
site_description: 'Documentation for the Progenetix oncogenomics resource'
site_author: Michael Baudis
copyright: '&copy; Copyright 2022, Michael Baudis and progenetix.org'
repo_name: 'progenetix-web'

repo_url: https://github.com/progenetix/progenetix-web
edit_uri: edit/main/docs/

###############################################################################

nav:
  - Documentation Home: index.md
  - News & Changes: news/index.md
  - Pages & Forms: ui.md
  - Services & API: services.md
  - Use Case Examples: use-cases.md
  - Classifications, Ontologies & Standards: classifications-and-ontologies.md
  - Publication Collection: publication-collection.md
  - Data Review: progenetix-data-review.md
  - Beacon+ & bycon: beaconplus.md
  - Technical Notes: technical-notes.md
  - Progenetix Data &#8599;: http://progenetix.org
  - Baudisgroup @ UZH &#8599;: http://info.baudisgroup.org
  # - Documentation PDF: pdf/progenetix-documentation.pdf

###############################################################################

markdown_extensions:
  - toc:
      toc_depth: 2-3
      permalink: true
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.magiclink:
      hide_protocol: true
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.saneheaders
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid   
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - mdx_gh_links:
      user: progenetix
      repo: progenetix-web
  - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg

###############################################################################

theme:
  # name: readthedocs
  name: material
  palette:
    primary: deep orange
  favicon: img/site-logo-topright.png
  logo: img/site-logo-topright.png
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      example: octicons/list-ordered-24
  features:
    - content.tabs.link
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - toc.integrate
  custom_dir: mkdocs_overrides
      
plugins:
    - search
    # - with-pdf:
    #     author: Progenetix
    #     output_path: pdf/progenetix-documentation.pdf
    - macros
    - mermaid2

extra:
  blog:
    dir: news
    author: Baudisgroup
#    author_image: img/site-logo-topright.png
    list_length: 50
    extended_preview: true
    excerpt_separator: <!--more-->
  social:
    - icon: fontawesome/brands/twitter 
      link: https://twitter.com/progenetix
    - icon: fontawesome/brands/github 
      link: https://github.com/progenetix
extra_css:
  - css/extra.css
extra_javascript:
  # - https://unpkg.com/mermaid/dist/mermaid.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
    